### ISSUE TITLE
Worldedit plugin cannot load

### ISSUE THREAD

**Issue by hunter688** [LapisBlue/Pore#10]
http://pastebin.com/ztWZmkAJ

Due thi does not work worldguard plugin too.

**Comment by simon816** [comment]
Pore is not ready yet, this is not at all surprising and is expected.
The error is very self-explanatory
```
Caused by: org.apache.commons.lang.NotImplementedException: Code is not implemented
        at blue.lapis.pore.impl.PoreServer.getHelpMap(PoreServer.java:641) ~[PoreServer.class:?]
```

**Comment by caseif** [comment]
Currently Pore does not officially support any plugins at the moment, as there is still much work to be done on both SpongeAPI and many of Pore's own systems. We'll be sure to make a public announcement when the plugin is in a semi-working state, though.

**Comment by Minecrell** [comment]
WorldEdit is available for Forge already, so I don't see a big point to invest a lot of time making it run on Pore. The native version would always run better than the Bukkit version running on Pore as a wrapper.

**Comment by hunter688** [comment]
But many plugins depends on worldedit plugin. Will be possible use forge version with bukkit plugins? For example worldguard - one of best protection plugins depends on worldedit.

**Comment by AesenV** [comment]
Pore is intended to be a complete reimplementation of Bukkit on top of Sponge, and so it should be able to run any plugins, as long as they don't use NMS. WorldEdit *does* use NMS, but it has graceful fallbacks for when it can't use NMS.

Ultimately, WorldEdit and WorldGuard are being ported to Sponge by their developer, who is actually the project lead, so it's nothing to be terribly concerned about.
