### ISSUE TITLE
Gradlew Build Failure; Execution Failed for task ':compileJava'

### ISSUE THREAD

**Issue by GizmoCodes** [LapisBlue/Pore#17]
I am trying to get Pore working for my server and I keep getting this when doing ./gradlew
http://pastebin.com/FL5HLgpH

System: Java 7, Update 80; Windows Tech Preview/Win 10, Git 1.9.5

**Comment by Minecrell** [comment]
You need to run `poredev update` before building Pore.

**Comment by GizmoCodes** [comment]
I did, but it appears to fail to apply the patch.
http://pastebin.com/Yif1Qq5p

**Comment by caseif** [comment]
Try recloning the Pore repository. I recall someone having this problem before and I think that did the trick.

**Comment by jamierocks** [comment]
What about use `./poredev update` through Powershell or Git Bash... @caseif they have sh support right?

**Comment by caseif** [comment]
@jamierocks The Windows and *nix scripts call the same Git commands, so it shouldn't make a difference which one is used. More likely it's an issue with the local history or something to that measure, which is why I suggested recloning entirely.

**Comment by GizmoCodes** [comment]
It applied the patch successfully after recloning the repo. Build Successful. Topic Closed.
