### ISSUE TITLE
Plugins not working properly

### ISSUE THREAD

**Issue by GershonR** [LapisBlue/Pore#35]
I installed 3 plugins using the latest Sponge version and Pore on Jenkins, all log files were created and all commands are appearing but non are doing there job.

- Antiad Doesen't do anything if a link or ip shows in the chat
- Logblock generates the mysql database but when a block is placed or broken it doesen't log it, created a plugins folder in the main directory and placed a materials.yml instead of using bukkit-plugins.  So if a block is placed or broken, when using a tool to check it, it says no changed found.
- Antixray does not seem to track any ore breaking, created a AntiXrayData folder also in the plugins folder, it created a bunch of player files with data but it does not update them.

**Comment by caseif** [comment]
Pore is still in an alpha state and lacks implementations for many features. As such, many plugins will not work properly.
