### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by BalloonChamp** [LapisBlue/Pore#37]
Hi, I loaded this plugin wiith HolographicDisplays and did /help and it gave me an error message. Can you please fix? Thanks!

**Comment by caseif** [comment]
Pore is still not yet complete, and many features lack implementations. As such, many plugins may not work properly.

**Comment by BalloonChamp** [comment]
Is development still happening a lot, or are you guys not developing a lot?

**Comment by caseif** [comment]
Currently the project is more or less on hiatus. We're not sure when or if we're going to pick full-scale development back up.
