### ISSUE TITLE
The implementation name is Pore

### ISSUE THREAD

**Issue by lexware** [LapisBlue/Pore#8]
Server#getName() is meant for the implementation name. https://github.com/LapisBlue/Pore/blob/aceb8b40b9e9bdd1e7ddee1883dab77ac2efee5c/src/main/java/blue/lapis/pore/impl/PoreServer.java#L167 so it should equal 'Pore'

**Comment by lexware** [comment]
This has been fixed.

**Comment by gratimax** [comment]
pointer to c302ed32ecf0e05a4 for reference
